development:
  adapter: postgresql
  encoding: unicode
  database: goalopedia_test_development
  pool: 5
  username: ajhoward
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: goalopedia_test_test
  pool: 5
  username: ajhoward
  password: 